name: flutter_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  googleapis: ^13.0.0
  googleapis_auth: ^1.4.0
  url_launcher: ^6.1.7
  http: ^1.3.0
  shelf: ^1.4.0
  google_sign_in: ^6.1.5
  google_sign_in_web: ^0.12.4+3

assets:
    - credentials.json

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
